kind: "Service"
apiVersion: v1
metadata:
  name: rabbitmq-management
  namespace: {{.namespace}}
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-management
      port: 15672
---
kind: Service
apiVersion: v1
metadata:
  namespace: {{.namespace}}
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
     nodePort: 31672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     nodePort: 30672
